package fr.fromation.inti.entities;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Adoption generated by hbm2java
 */
@Entity
@Table(name = "adoption", catalog = "adopt_a_pet")
public class Adoption implements java.io.Serializable {

	private int idadoption;
	private int iduser;
	private int idpet;
	private Date dateDemande;
	private byte validationProfile;
	private byte validationPaiement;
	private Set<Paiement> paiements = new HashSet<Paiement>(0);

	public Adoption() {
	}

	public Adoption(int idadoption, int iduser, int idpet, Date dateDemande, byte validationProfile,
			byte validationPaiement) {
		this.idadoption = idadoption;
		this.iduser = iduser;
		this.idpet = idpet;
		this.dateDemande = dateDemande;
		this.validationProfile = validationProfile;
		this.validationPaiement = validationPaiement;
	}

	public Adoption(int idadoption, int iduser, int idpet, Date dateDemande, byte validationProfile,
			byte validationPaiement, Set<Paiement> paiements) {
		this.idadoption = idadoption;
		this.iduser = iduser;
		this.idpet = idpet;
		this.dateDemande = dateDemande;
		this.validationProfile = validationProfile;
		this.validationPaiement = validationPaiement;
		this.paiements = paiements;
	}

	@Id

	@Column(name = "idadoption", unique = true, nullable = false)
	public int getIdadoption() {
		return this.idadoption;
	}

	public void setIdadoption(int idadoption) {
		this.idadoption = idadoption;
	}

	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Column(name = "idpet", nullable = false)
	public int getIdpet() {
		return this.idpet;
	}

	public void setIdpet(int idpet) {
		this.idpet = idpet;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_demande", nullable = false, length = 19)
	public Date getDateDemande() {
		return this.dateDemande;
	}

	public void setDateDemande(Date dateDemande) {
		this.dateDemande = dateDemande;
	}

	@Column(name = "validation_profile", nullable = false)
	public byte getValidationProfile() {
		return this.validationProfile;
	}

	public void setValidationProfile(byte validationProfile) {
		this.validationProfile = validationProfile;
	}

	@Column(name = "validation_paiement", nullable = false)
	public byte getValidationPaiement() {
		return this.validationPaiement;
	}

	public void setValidationPaiement(byte validationPaiement) {
		this.validationPaiement = validationPaiement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adoption")
	public Set<Paiement> getPaiements() {
		return this.paiements;
	}

	public void setPaiements(Set<Paiement> paiements) {
		this.paiements = paiements;
	}

}
