package fr.fromation.inti.entities;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Centre generated by hbm2java
 */
@Entity
@Table(name = "centre", catalog = "adopt_a_pet")
public class Centre implements java.io.Serializable {

	private CentreId id;

	public Centre() {
	}

	public Centre(CentreId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "iduser", column = @Column(name = "iduser", nullable = false)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 45)),
			@AttributeOverride(name = "deptid", column = @Column(name = "deptid", nullable = false)),
			@AttributeOverride(name = "tel", column = @Column(name = "tel", length = 45)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 45)),
			@AttributeOverride(name = "postalCode", column = @Column(name = "postal_code", length = 45)) })
	public CentreId getId() {
		return this.id;
	}

	public void setId(CentreId id) {
		this.id = id;
	}

}
