package fr.fromation.inti.entities;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departement generated by hbm2java
 */
@Entity
@Table(name = "departement", catalog = "adopt_a_pet")
public class Departement implements java.io.Serializable {

	private int deptid;
	private String name;

	public Departement() {
	}

	public Departement(int deptid, String name) {
		this.deptid = deptid;
		this.name = name;
	}

	@Id

	@Column(name = "deptid", unique = true, nullable = false)
	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
