package fr.fromation.inti.entities;
// Generated 15 janv. 2020 16:53:54 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Transfert generated by hbm2java
 */
@Entity
@Table(name = "transfert", catalog = "adopt_a_pet")
public class Transfert implements java.io.Serializable {

	private Integer idtransfert;
	private Pet pet;
	private User userByNewIdUser;
	private User userByIduser;

	public Transfert() {
	}

	public Transfert(Pet pet, User userByNewIdUser, User userByIduser) {
		this.pet = pet;
		this.userByNewIdUser = userByNewIdUser;
		this.userByIduser = userByIduser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtransfert", unique = true, nullable = false)
	public Integer getIdtransfert() {
		return this.idtransfert;
	}

	public void setIdtransfert(Integer idtransfert) {
		this.idtransfert = idtransfert;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpet", nullable = false)
	public Pet getPet() {
		return this.pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "new_id_user", nullable = false)
	public User getUserByNewIdUser() {
		return this.userByNewIdUser;
	}

	public void setUserByNewIdUser(User userByNewIdUser) {
		this.userByNewIdUser = userByNewIdUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser", nullable = false)
	public User getUserByIduser() {
		return this.userByIduser;
	}

	public void setUserByIduser(User userByIduser) {
		this.userByIduser = userByIduser;
	}

}
