-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 10:54:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adopt_a_pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adopt_a_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adopt_a_pet` DEFAULT CHARACTER SET latin1 ;
USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`adoption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`adoption` (
  `idadoption` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idpet` INT NOT NULL,
  `date_demande` DATETIME NOT NULL,
  `validation_profile` TINYINT NOT NULL,
  `validation_paiement` TINYINT NOT NULL,
  PRIMARY KEY (`idadoption`),
  INDEX `fk_adoption_user1_idx` (`iduser` ASC),
  INDEX `fk_adoption_pet1_idx` (`idpet` ASC),
  CONSTRAINT `fk_adoption_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adoption_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`centre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`centre` (
  `iduser` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deptid` INT(11) NOT NULL,
  `tel` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  INDEX `fk_centre_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_centre_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`departement` (
  `deptid` INT(11) NOT NULL,
  `departement_code` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deptid`),
  CONSTRAINT `fk_departement_user`
    FOREIGN KEY (`deptid`)
    REFERENCES `adopt_a_pet`.`user` (`deptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- phpMyAdmin SQL Dump
-- version 4.0.6deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 09, 2013 at 06:10 PM
-- Server version: 5.5.34-0ubuntu0.13.10.1
-- PHP Version: 5.5.3-1ubuntu2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


--
-- Dumping data for table `departement`
--

INSERT INTO `departement` (`deptid`, `departement_code`,`name`) VALUES
(1, '01', 'Ain'),
(2, '02', 'Aisne'),
(3, '03', 'Allier'),
(5, '05', 'Hautes-Alpes'),
(4, '04', 'Alpes-de-Haute-Provence'),
(6, '06', 'Alpes-Maritimes'),
(7, '07', 'Ardèche'),
(8, '08', 'Ardennes'),
(9, '09', 'Ariège'),
(10, '10', 'Aube'),
(11, '11', 'Aude'),
(12, '12', 'Aveyron'),
(13, '13', 'Bouches-du-Rhône'),
(14, '14', 'Calvados'),
(15, '15', 'Cantal'),
(16, '16', 'Charente'),
(17, '17', 'Charente-Maritime'),
(18, '18', 'Cher'),
(19, '19', 'Corrèze'),
(20, '2a', 'Corse-du-sud'),
(21, '2b', 'Haute-corse'),
(22, '21', 'Côte-d''or'),
(23, '22', 'Côtes-d''armor'),
(24, '23', 'Creuse'),
(25, '24', 'Dordogne'),
(26, '25', 'Doubs'),
(27, '26', 'Drôme'),
(28, '27', 'Eure'),
(29, '28', 'Eure-et-Loir'),
(30, '29', 'Finistère'),
(31, '30', 'Gard'),
(32, '31', 'Haute-Garonne'),
(33, '32', 'Gers'),
(34, '33', 'Gironde'),
(35, '34', 'Hérault'),
(36, '35', 'Ile-et-Vilaine'),
(37, '36', 'Indre'),
(38, '37', 'Indre-et-Loire'),
(39, '38', 'Isère'),
(40, '39', 'Jura'),
(41, '40', 'Landes'),
(42, '41', 'Loir-et-Cher'),
(43, '42', 'Loire'),
(44, '43', 'Haute-Loire'),
(45, '44', 'Loire-Atlantique'),
(46, '45', 'Loiret'),
(47, '46', 'Lot'),
(48, '47', 'Lot-et-Garonne'),
(49, '48', 'Lozère'),
(50, '49', 'Maine-et-Loire'),
(51, '50', 'Manche'),
(52, '51', 'Marne'),
(53, '52', 'Haute-Marne'),
(54, '53', 'Mayenne'),
(55, '54', 'Meurthe-et-Moselle'),
(56, '55', 'Meuse'),
(57, '56', 'Morbihan'),
(58, '57', 'Moselle'),
(59, '58', 'Nièvre'),
(60, '59', 'Nord'),
(61, '60', 'Oise'),
(62, '61', 'Orne'),
(63, '62', 'Pas-de-Calais'),
(64, '63', 'Puy-de-Dôme'),
(65, '64', 'Pyrénées-Atlantiques'),
(66, '65', 'Hautes-Pyrénées'),
(67, '66', 'Pyrénées-Orientales'),
(68, '67', 'Bas-Rhin'),
(69, '68', 'Haut-Rhin'),
(70, '69', 'Rhône'),
(71, '70', 'Haute-Saône'),
(72, '71', 'Saône-et-Loire'),
(73, '72', 'Sarthe'),
(74, '73', 'Savoie'),
(75, '74', 'Haute-Savoie'),
(76, '75', 'Paris'),
(77, '76', 'Seine-Maritime'),
(78, '77', 'Seine-et-Marne'),
(79, '78', 'Yvelines'),
(80, '79', 'Deux-Sèvres'),
(81, '80', 'Somme'),
(82, '81', 'Tarn'),
(83, '82', 'Tarn-et-Garonne'),
(84, '83', 'Var'),
(85, '84', 'Vaucluse'),
(86, '85', 'Vendée'),
(87, '86', 'Vienne'),
(88, '87', 'Haute-Vienne'),
(89, '88', 'Vosges'),
(90, '89', 'Yonne'),
(91, '90', 'Territoire de Belfort'),
(92, '91', 'Essonne'),
(93, '92', 'Hauts-de-Seine'),
(94, '93', 'Seine-Saint-Denis'),
(95, '94', 'Val-de-Marne'),
(96, '95', 'Val-d''oise'),
(97, '976', 'Mayotte'),
(98, '971', 'Guadeloupe'),
(99, '973', 'Guyane'),
(100, '972', 'Martinique'),
(101, '974', 'Réunion');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;



-- -----------------------------------------------------
-- Table `adopt_a_pet`.`historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`historique` (
  `idhistorique` INT NOT NULL,
  `idpet` INT NOT NULL,
  `iduser` INT NOT NULL,
  `deptid` INT NOT NULL,
  `debut_sejour` DATETIME NOT NULL,
  `fin_sejour` DATETIME NULL,
  PRIMARY KEY (`idhistorique`),
  INDEX `fk_historique_pet1_idx` (`idpet` ASC),
  INDEX `fk_historique_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_historique_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historique_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`individual` (
  `iduser` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` INT(11) NOT NULL,
  INDEX `fk_individual_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_individual_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`paiement` (
  `idpaiement` INT NOT NULL AUTO_INCREMENT,
  `idadoption` INT NOT NULL,
  PRIMARY KEY (`idpaiement`),
  INDEX `fk_paiement_adoption1_idx` (`idadoption` ASC),
  CONSTRAINT `fk_paiement_adoption1`
    FOREIGN KEY (`idadoption`)
    REFERENCES `adopt_a_pet`.`adoption` (`idadoption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`pet` (
  `idpet` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `race` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `iduser` INT(11) NULL DEFAULT NULL,
  `deptid` INT(11) NOT NULL,
  PRIMARY KEY (`idpet`),
  INDEX `fk_pet_historique1_idx` (`deptid` ASC),
  CONSTRAINT `fk_pet_user1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`user` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_historique1`
    FOREIGN KEY (`deptid`)
    REFERENCES `adopt_a_pet`.`historique` (`deptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_departement1`
    FOREIGN KEY (`deptid`)
    REFERENCES `adopt_a_pet`.`departement` (`deptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`title` (
  `idtitle` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtitle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`transfert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`transfert` (
  `idtransfert` INT NOT NULL,
  `idpet` INT NOT NULL,
  `iduser` INT NOT NULL,
  `new_id_user` INT NOT NULL,
  PRIMARY KEY (`idtransfert`),
  INDEX `fk_transfert_pet1_idx` (`idpet` ASC),
  INDEX `fk_transfert_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_transfert_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfert_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `idpet` INT(11) NULL DEFAULT NULL,
  `deptid` INT(11) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `date_creation` DATETIME NULL,
  `date_fermeture` DATETIME NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_title1_idx` (`title` ASC),
  CONSTRAINT `fk_user_title1`
    FOREIGN KEY (`title`)
    REFERENCES `adopt_a_pet`.`title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- procedure get_historic
-- -----------------------------------------------------

DELIMITER $$
USE `adopt_a_pet`$$
CREATE PROCEDURE `get_historic` ()
BEGIN

END$$

DELIMITER ;
USE `adopt_a_pet`;

DELIMITER $$
USE `adopt_a_pet`$$
CREATE DEFINER=`root`@`localhost` TRIGGER user_create_date BEFORE INSERT ON user
	FOR EACH ROW SET NEW.create_date = NOW()$$

USE `adopt_a_pet`$$
CREATE DEFINER=`root`@`localhost` TRIGGER user_delete_date AFTER DELETE ON user
	FOR EACH ROW SET NEW.create_date = NOW()$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
