-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 10:54:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adopt_a_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adopt_a_pet` DEFAULT CHARACTER SET latin1 ;
USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`adoption`
-- -----------------------------------------------------
CREATE TABLE `adoption` (
  `idadoption` int(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `idpet` int(11) NOT NULL,
  `date_demande` datetime NOT NULL,
  `validation_profile` tinyint(4) NOT NULL,
  `validation_paiement` tinyint(4) NOT NULL,
  PRIMARY KEY (`idadoption`),
  KEY `iduser_user_adoption_idx` (`iduser`),
  KEY `idpet_pet_adoption_idx` (`idpet`),
  CONSTRAINT `idpet_pet_adoption` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_adoption` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`centre`
-- -----------------------------------------------------
CREATE TABLE `centre` (
  `idcentre` int(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `name` varchar(45) NOT NULL,
  `deptid` int(11) NOT NULL,
  `tel` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `postal_code` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idcentre`),
  KEY `iduser_user_centre_idx` (`iduser`),
  KEY `deptid_departement_centre_idx` (`deptid`),
  CONSTRAINT `deptid_departement_centre` FOREIGN KEY (`deptid`) REFERENCES `departement` (`deptid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_centre` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `centre` (`iduser`,`name`,`deptid`,`tel`,`city`,`postal_code`) 
VALUES ("1","Centre_Normandie","51 ","02 82 23 08 16","Granville","50400"),
("2","Centre_Ile-de-France","94","01 86 70 43 64","Neuilly-Plaisance","93330"),
("3","Centre_Haute-Garonne","32","05 38 39 56 74","Toulouse","31100");

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`departement`
-- -----------------------------------------------------
CREATE TABLE `departement` (
  `deptid` int(11) NOT NULL,
  `departement_code` int(11) NOT NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`deptid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- phpMyAdmin SQL Dump
-- version 4.0.6deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 09, 2013 at 06:10 PM
-- Server version: 5.5.34-0ubuntu0.13.10.1
-- PHP Version: 5.5.3-1ubuntu2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


--
-- Dumping data for table `departement`
--

INSERT INTO `departement` (`deptid`, `departement_code`,`name`) VALUES
(1, '01', 'Ain'),
(2, '02', 'Aisne'),
(3, '03', 'Allier'),
(5, '05', 'Hautes-Alpes'),
(4, '04', 'Alpes-de-Haute-Provence'),
(6, '06', 'Alpes-Maritimes'),
(7, '07', 'Ardèche'),
(8, '08', 'Ardennes'),
(9, '09', 'Ariège'),
(10, '10', 'Aube'),
(11, '11', 'Aude'),
(12, '12', 'Aveyron'),
(13, '13', 'Bouches-du-Rhône'),
(14, '14', 'Calvados'),
(15, '15', 'Cantal'),
(16, '16', 'Charente'),
(17, '17', 'Charente-Maritime'),
(18, '18', 'Cher'),
(19, '19', 'Corrèze'),
(20, '2a', 'Corse-du-sud'),
(21, '2b', 'Haute-corse'),
(22, '21', 'Côte-d''or'),
(23, '22', 'Côtes-d''armor'),
(24, '23', 'Creuse'),
(25, '24', 'Dordogne'),
(26, '25', 'Doubs'),
(27, '26', 'Drôme'),
(28, '27', 'Eure'),
(29, '28', 'Eure-et-Loir'),
(30, '29', 'Finistère'),
(31, '30', 'Gard'),
(32, '31', 'Haute-Garonne'),
(33, '32', 'Gers'),
(34, '33', 'Gironde'),
(35, '34', 'Hérault'),
(36, '35', 'Ile-et-Vilaine'),
(37, '36', 'Indre'),
(38, '37', 'Indre-et-Loire'),
(39, '38', 'Isère'),
(40, '39', 'Jura'),
(41, '40', 'Landes'),
(42, '41', 'Loir-et-Cher'),
(43, '42', 'Loire'),
(44, '43', 'Haute-Loire'),
(45, '44', 'Loire-Atlantique'),
(46, '45', 'Loiret'),
(47, '46', 'Lot'),
(48, '47', 'Lot-et-Garonne'),
(49, '48', 'Lozère'),
(50, '49', 'Maine-et-Loire'),
(51, '50', 'Manche'),
(52, '51', 'Marne'),
(53, '52', 'Haute-Marne'),
(54, '53', 'Mayenne'),
(55, '54', 'Meurthe-et-Moselle'),
(56, '55', 'Meuse'),
(57, '56', 'Morbihan'),
(58, '57', 'Moselle'),
(59, '58', 'Nièvre'),
(60, '59', 'Nord'),
(61, '60', 'Oise'),
(62, '61', 'Orne'),
(63, '62', 'Pas-de-Calais'),
(64, '63', 'Puy-de-Dôme'),
(65, '64', 'Pyrénées-Atlantiques'),
(66, '65', 'Hautes-Pyrénées'),
(67, '66', 'Pyrénées-Orientales'),
(68, '67', 'Bas-Rhin'),
(69, '68', 'Haut-Rhin'),
(70, '69', 'Rhône'),
(71, '70', 'Haute-Saône'),
(72, '71', 'Saône-et-Loire'),
(73, '72', 'Sarthe'),
(74, '73', 'Savoie'),
(75, '74', 'Haute-Savoie'),
(76, '75', 'Paris'),
(77, '76', 'Seine-Maritime'),
(78, '77', 'Seine-et-Marne'),
(79, '78', 'Yvelines'),
(80, '79', 'Deux-Sèvres'),
(81, '80', 'Somme'),
(82, '81', 'Tarn'),
(83, '82', 'Tarn-et-Garonne'),
(84, '83', 'Var'),
(85, '84', 'Vaucluse'),
(86, '85', 'Vendée'),
(87, '86', 'Vienne'),
(88, '87', 'Haute-Vienne'),
(89, '88', 'Vosges'),
(90, '89', 'Yonne'),
(91, '90', 'Territoire de Belfort'),
(92, '91', 'Essonne'),
(93, '92', 'Hauts-de-Seine'),
(94, '93', 'Seine-Saint-Denis'),
(95, '94', 'Val-de-Marne'),
(96, '95', 'Val-d''oise'),
(97, '976', 'Mayotte'),
(98, '971', 'Guadeloupe'),
(99, '973', 'Guyane'),
(100, '972', 'Martinique'),
(101, '974', 'Réunion');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;



-- -----------------------------------------------------
-- Table `adopt_a_pet`.`historique`
-- -----------------------------------------------------
CREATE TABLE `historique` (
  `idhistorique` int(11) NOT NULL AUTO_INCREMENT,
  `idpet` int(11) NOT NULL,
  `iduser` int(11) NOT NULL,
  `deptid` int(11) NOT NULL,
  `debut_sejour` datetime NOT NULL,
  `fin_sejour` datetime DEFAULT NULL,
  PRIMARY KEY (`idhistorique`),
  KEY `idpet_idx` (`idpet`),
  KEY `deptid_idx` (`deptid`),
  KEY `iduser_user_historique_idx` (`iduser`),
  CONSTRAINT `deptid_departement_historique` FOREIGN KEY (`deptid`) REFERENCES `departement` (`deptid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `idpet_pet_historique` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_historique` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`individual`
-- -----------------------------------------------------
CREATE TABLE `individual` (
  `idindvidual` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `mail` varchar(45) NOT NULL,
  `tel` varchar(45) NOT NULL,
  `adress` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `postal_code` int(11) NOT NULL,
  PRIMARY KEY (`idindvidual`),
  KEY `iduser_user_individual_idx` (`iduser`),
  CONSTRAINT `iduser_user_individual` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`paiement`
-- -----------------------------------------------------
CREATE TABLE `paiement` (
  `idpaiement` int(11) NOT NULL AUTO_INCREMENT,
  `idadoption` int(11) NOT NULL,
  PRIMARY KEY (`idpaiement`),
  KEY `idadoption_adoption_paiement_idx` (`idadoption`),
  CONSTRAINT `idadoption_adoption_paiement` FOREIGN KEY (`idadoption`) REFERENCES `adoption` (`idadoption`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`title`
-- -----------------------------------------------------
CREATE TABLE `title` (
  `idtitle` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(45) NOT NULL,
  PRIMARY KEY (`idtitle`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `title` (`title`) VALUES
("admin"),("F.A"),("User"),("Centre");


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`transfert`
-- -----------------------------------------------------
CREATE TABLE `transfert` (
  `idtransfert` int(11) NOT NULL AUTO_INCREMENT,
  `idpet` int(11) NOT NULL,
  `iduser` int(11) NOT NULL,
  `new_id_user` int(11) NOT NULL,
  PRIMARY KEY (`idtransfert`),
  KEY `idpet_pet_transfert_idx` (`idpet`),
  KEY `iduser_user_transfert_idx` (`iduser`),
  KEY `newiduser_user_transfert_idx` (`new_id_user`),
  CONSTRAINT `idpet_pet_transfert` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_transfert` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `newiduser_user_transfert` FOREIGN KEY (`new_id_user`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`categorie`
-- -----------------------------------------------------
CREATE TABLE `categorie` (
  `idcat` int(11) NOT NULL AUTO_INCREMENT,
  `categorie` varchar(45) NOT NULL,
  PRIMARY KEY (`idcat`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `categorie` (`categorie`) 
VALUES ("CHIEN"),("CHAT"),("NAC");

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`user`
-- -----------------------------------------------------
CREATE TABLE `user` (
  `iduser` int(11) NOT NULL AUTO_INCREMENT,
  `idpet` int(11),
  `deptid` int(11) NOT NULL,
  `username` varchar(45) NOT NULL,
  `password` varchar(45) NOT NULL,
  `idtitle` int(11) NOT NULL,
  `date_creation` datetime DEFAULT NULL,
  `date_fermeture` datetime DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  KEY `idpet_pet_user_idx` (`idpet`),
  KEY `deptid_departement_user_idx` (`deptid`),
  KEY `idtitle_title_user_idx` (`idtitle`),
  CONSTRAINT `deptid_departement_user` FOREIGN KEY (`deptid`) REFERENCES `departement` (`deptid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `idpet_pet_user` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `idtitle_title_user` FOREIGN KEY (`idtitle`) REFERENCES `title` (`idtitle`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `user` (`deptid`,`username`,`password`,`idtitle`) 
VALUES ("51","C_N","petN2020","4"),
("94","C_IDF","petIDF2020","4"),
("32","C_HG","petHG2020","4");


USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`pet`
-- -----------------------------------------------------
CREATE TABLE `pet` (
  `idpet` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `idcat` int(11) NOT NULL,
  `race` varchar(45) DEFAULT NULL,
  `age` varchar(45) DEFAULT NULL,
  `iduser` int(11) NOT NULL,
  `deptid` int(11) NOT NULL,
  PRIMARY KEY (`idpet`),
  KEY `idcat_categorie_pet_idx` (`idcat`),
  KEY `iduser_user_pet_idx` (`iduser`),
  CONSTRAINT `idcat_categorie_pet` FOREIGN KEY (`idcat`) REFERENCES `categorie` (`idcat`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_pet` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `pet` (`name`,`idcat`,`race`,`iduser`, `deptid`) 
VALUES ("Médor","1","Labrador","1","51"),
("Capucine","3","Hamster-russe","2","94"),
("Felix","2","Européen","3","32");

-- -----------------------------------------------------
-- procedure get_historic
-- -----------------------------------------------------

DELIMITER $$
USE `adopt_a_pet`$$
CREATE PROCEDURE `get_historic` ()
BEGIN

END$$

DELIMITER ;
USE `adopt_a_pet`;

"DELIMITER $$
USE `adopt_a_pet`$$
CREATE DEFINER=`root`@`localhost` TRIGGER user_create_date BEFORE INSERT ON user
	FOR EACH ROW SET USER.date_creation = NOW()$$

USE `adopt_a_pet`$$
CREATE DEFINER=`root`@`localhost` TRIGGER user_delete_date AFTER DELETE ON user
	FOR EACH ROW SET USER.date_fermeture = NOW()$$"


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
