-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 10:54:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adopt_a_pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema adopt_a_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adopt_a_pet` DEFAULT CHARACTER SET latin1 ;
USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`adoption`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`adoption` (
  `idadoption` INT NOT NULL,
  `iduser` INT NOT NULL,
  `idpet` INT NOT NULL,
  `date_demande` DATETIME NOT NULL,
  `validation_profile` TINYINT NOT NULL,
  `validation_paiement` TINYINT NOT NULL,
  PRIMARY KEY (`idadoption`),
  INDEX `fk_adoption_user1_idx` (`iduser` ASC),
  INDEX `fk_adoption_pet1_idx` (`idpet` ASC),
  CONSTRAINT `fk_adoption_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_adoption_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`centre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`centre` (
  `iduser` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `deptid` INT(11) NOT NULL,
  `tel` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  INDEX `fk_centre_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_centre_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`departement` (
  `deptid` INT(11) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`deptid`),
  CONSTRAINT `fk_departement_user`
    FOREIGN KEY (`deptid`)
    REFERENCES `adopt_a_pet`.`user` (`deptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`historique` (
  `idhistorique` INT NOT NULL,
  `idpet` INT NOT NULL,
  `iduser` INT NOT NULL,
  `deptid` INT NOT NULL,
  `debut_sejour` DATETIME NOT NULL,
  `fin_sejour` DATETIME NULL,
  PRIMARY KEY (`idhistorique`),
  INDEX `fk_historique_pet1_idx` (`idpet` ASC),
  INDEX `fk_historique_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_historique_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historique_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`individual`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`individual` (
  `iduser` INT(11) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `tel` VARCHAR(45) NOT NULL,
  `adress` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL DEFAULT NULL,
  `postal_code` INT(11) NOT NULL,
  INDEX `fk_individual_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_individual_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`paiement` (
  `idpaiement` INT NOT NULL AUTO_INCREMENT,
  `idadoption` INT NOT NULL,
  PRIMARY KEY (`idpaiement`),
  INDEX `fk_paiement_adoption1_idx` (`idadoption` ASC),
  CONSTRAINT `fk_paiement_adoption1`
    FOREIGN KEY (`idadoption`)
    REFERENCES `adopt_a_pet`.`adoption` (`idadoption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`pet` (
  `idpet` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `race` VARCHAR(45) NULL DEFAULT NULL,
  `age` VARCHAR(45) NULL DEFAULT NULL,
  `iduser` INT(11) NULL DEFAULT NULL,
  `deptid` INT(11) NOT NULL,
  PRIMARY KEY (`idpet`),
  INDEX `fk_pet_historique1_idx` (`deptid` ASC),
  CONSTRAINT `fk_pet_user1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`user` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_historique1`
    FOREIGN KEY (`deptid`)
    REFERENCES `adopt_a_pet`.`historique` (`deptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pet_departement1`
    FOREIGN KEY (`deptid`)
    REFERENCES `adopt_a_pet`.`departement` (`deptid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`title` (
  `idtitle` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtitle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`transfert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`transfert` (
  `idtransfert` INT NOT NULL,
  `idpet` INT NOT NULL,
  `iduser` INT NOT NULL,
  `new_id_user` INT NOT NULL,
  PRIMARY KEY (`idtransfert`),
  INDEX `fk_transfert_pet1_idx` (`idpet` ASC),
  INDEX `fk_transfert_user1_idx` (`iduser` ASC),
  CONSTRAINT `fk_transfert_pet1`
    FOREIGN KEY (`idpet`)
    REFERENCES `adopt_a_pet`.`pet` (`idpet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transfert_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `adopt_a_pet`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adopt_a_pet`.`user` (
  `iduser` INT(11) NOT NULL AUTO_INCREMENT,
  `idpet` INT(11) NULL DEFAULT NULL,
  `deptid` INT(11) NOT NULL,
  `pseudo` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `date_creation` DATETIME NULL,
  `date_fermeture` DATETIME NULL,
  PRIMARY KEY (`iduser`),
  INDEX `fk_user_title1_idx` (`title` ASC),
  CONSTRAINT `fk_user_title1`
    FOREIGN KEY (`title`)
    REFERENCES `adopt_a_pet`.`title` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- procedure get_historic
-- -----------------------------------------------------

DELIMITER $$
USE `adopt_a_pet`$$
CREATE PROCEDURE `get_historic` ()
BEGIN

END$$

DELIMITER ;
USE `adopt_a_pet`;

DELIMITER $$
USE `adopt_a_pet`$$
CREATE DEFINER=`root`@`localhost` TRIGGER user_create_date BEFORE INSERT ON user
	FOR EACH ROW SET NEW.create_date = NOW()$$

USE `adopt_a_pet`$$
CREATE DEFINER=`root`@`localhost` TRIGGER user_delete_date AFTER DELETE ON user
	FOR EACH ROW SET NEW.create_date = NOW()$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
