package fr.fromation.inti;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CentreId generated by hbm2java
 */
@Embeddable
public class CentreId implements java.io.Serializable {

	private int iduser;
	private String name;
	private int deptid;
	private String tel;
	private String city;
	private String postalCode;

	public CentreId() {
	}

	public CentreId(int iduser, String name, int deptid) {
		this.iduser = iduser;
		this.name = name;
		this.deptid = deptid;
	}

	public CentreId(int iduser, String name, int deptid, String tel, String city, String postalCode) {
		this.iduser = iduser;
		this.name = name;
		this.deptid = deptid;
		this.tel = tel;
		this.city = city;
		this.postalCode = postalCode;
	}

	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "deptid", nullable = false)
	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	@Column(name = "tel", length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postal_code", length = 45)
	public String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CentreId))
			return false;
		CentreId castOther = (CentreId) other;

		return (this.getIduser() == castOther.getIduser())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName().equals(castOther.getName())))
				&& (this.getDeptid() == castOther.getDeptid())
				&& ((this.getTel() == castOther.getTel()) || (this.getTel() != null && castOther.getTel() != null
						&& this.getTel().equals(castOther.getTel())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getPostalCode() == castOther.getPostalCode())
						|| (this.getPostalCode() != null && castOther.getPostalCode() != null
								&& this.getPostalCode().equals(castOther.getPostalCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIduser();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getDeptid();
		result = 37 * result + (getTel() == null ? 0 : this.getTel().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getPostalCode() == null ? 0 : this.getPostalCode().hashCode());
		return result;
	}

}
