package fr.fromation.inti;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historique generated by hbm2java
 */
@Entity
@Table(name = "historique", catalog = "adopt_a_pet")
public class Historique implements java.io.Serializable {

	private int idhistorique;
	private int idpet;
	private int iduser;
	private int deptid;
	private Date debutSejour;
	private Date finSejour;

	public Historique() {
	}

	public Historique(int idhistorique, int idpet, int iduser, int deptid, Date debutSejour) {
		this.idhistorique = idhistorique;
		this.idpet = idpet;
		this.iduser = iduser;
		this.deptid = deptid;
		this.debutSejour = debutSejour;
	}

	public Historique(int idhistorique, int idpet, int iduser, int deptid, Date debutSejour, Date finSejour) {
		this.idhistorique = idhistorique;
		this.idpet = idpet;
		this.iduser = iduser;
		this.deptid = deptid;
		this.debutSejour = debutSejour;
		this.finSejour = finSejour;
	}

	@Id

	@Column(name = "idhistorique", unique = true, nullable = false)
	public int getIdhistorique() {
		return this.idhistorique;
	}

	public void setIdhistorique(int idhistorique) {
		this.idhistorique = idhistorique;
	}

	@Column(name = "idpet", nullable = false)
	public int getIdpet() {
		return this.idpet;
	}

	public void setIdpet(int idpet) {
		this.idpet = idpet;
	}

	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Column(name = "deptid", nullable = false)
	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "debut_sejour", nullable = false, length = 19)
	public Date getDebutSejour() {
		return this.debutSejour;
	}

	public void setDebutSejour(Date debutSejour) {
		this.debutSejour = debutSejour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fin_sejour", length = 19)
	public Date getFinSejour() {
		return this.finSejour;
	}

	public void setFinSejour(Date finSejour) {
		this.finSejour = finSejour;
	}

}
