package fr.fromation.inti;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Individual generated by hbm2java
 */
@Entity
@Table(name = "individual", catalog = "adopt_a_pet")
public class Individual implements java.io.Serializable {

	private IndividualId id;

	public Individual() {
	}

	public Individual(IndividualId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "iduser", column = @Column(name = "iduser", nullable = false)),
			@AttributeOverride(name = "firstName", column = @Column(name = "first_name", nullable = false, length = 45)),
			@AttributeOverride(name = "lastName", column = @Column(name = "last_name", nullable = false, length = 45)),
			@AttributeOverride(name = "mail", column = @Column(name = "mail", nullable = false, length = 45)),
			@AttributeOverride(name = "tel", column = @Column(name = "tel", nullable = false, length = 45)),
			@AttributeOverride(name = "adress", column = @Column(name = "adress", length = 45)),
			@AttributeOverride(name = "city", column = @Column(name = "city", length = 45)),
			@AttributeOverride(name = "postalCode", column = @Column(name = "postal_code", nullable = false)) })
	public IndividualId getId() {
		return this.id;
	}

	public void setId(IndividualId id) {
		this.id = id;
	}

}
