package fr.fromation.inti;
// Generated 14 janv. 2020 16:37:00 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * IndividualId generated by hbm2java
 */
@Embeddable
public class IndividualId implements java.io.Serializable {

	private int iduser;
	private String firstName;
	private String lastName;
	private String mail;
	private String tel;
	private String adress;
	private String city;
	private int postalCode;

	public IndividualId() {
	}

	public IndividualId(int iduser, String firstName, String lastName, String mail, String tel, int postalCode) {
		this.iduser = iduser;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mail = mail;
		this.tel = tel;
		this.postalCode = postalCode;
	}

	public IndividualId(int iduser, String firstName, String lastName, String mail, String tel, String adress,
			String city, int postalCode) {
		this.iduser = iduser;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mail = mail;
		this.tel = tel;
		this.adress = adress;
		this.city = city;
		this.postalCode = postalCode;
	}

	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "mail", nullable = false, length = 45)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "tel", nullable = false, length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "adress", length = 45)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postal_code", nullable = false)
	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IndividualId))
			return false;
		IndividualId castOther = (IndividualId) other;

		return (this.getIduser() == castOther.getIduser())
				&& ((this.getFirstName() == castOther.getFirstName()) || (this.getFirstName() != null
						&& castOther.getFirstName() != null && this.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this.getLastName() != null
						&& castOther.getLastName() != null && this.getLastName().equals(castOther.getLastName())))
				&& ((this.getMail() == castOther.getMail()) || (this.getMail() != null && castOther.getMail() != null
						&& this.getMail().equals(castOther.getMail())))
				&& ((this.getTel() == castOther.getTel()) || (this.getTel() != null && castOther.getTel() != null
						&& this.getTel().equals(castOther.getTel())))
				&& ((this.getAdress() == castOther.getAdress()) || (this.getAdress() != null
						&& castOther.getAdress() != null && this.getAdress().equals(castOther.getAdress())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& (this.getPostalCode() == castOther.getPostalCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIduser();
		result = 37 * result + (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result + (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result + (getMail() == null ? 0 : this.getMail().hashCode());
		result = 37 * result + (getTel() == null ? 0 : this.getTel().hashCode());
		result = 37 * result + (getAdress() == null ? 0 : this.getAdress().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + this.getPostalCode();
		return result;
	}

}
