package fr.formation.inti.entities;
// Generated 15 janv. 2020 16:53:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", catalog = "adopt_a_pet")
public class Categorie implements java.io.Serializable {

	private Integer idcat;
	private String categorie;
	private Set<Pet> pets = new HashSet<Pet>(0);

	public Categorie() {
	}

	public Categorie(String categorie) {
		this.categorie = categorie;
	}

	public Categorie(String categorie, Set<Pet> pets) {
		this.categorie = categorie;
		this.pets = pets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcat", unique = true, nullable = false)
	public Integer getIdcat() {
		return this.idcat;
	}

	public void setIdcat(Integer idcat) {
		this.idcat = idcat;
	}

	@Column(name = "categorie", nullable = false, length = 45)
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categorie")
	public Set<Pet> getPets() {
		return this.pets;
	}

	public void setPets(Set<Pet> pets) {
		this.pets = pets;
	}

}
