package fr.formation.inti.entities;
// Generated 15 janv. 2020 16:53:54 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historique generated by hbm2java
 */
@Entity
@Table(name = "historique", catalog = "adopt_a_pet")
public class Historique implements java.io.Serializable {

	private Integer idhistorique;
	private Departement departement;
	private Pet pet;
	private User user;
	private Date debutSejour;
	private Date finSejour;

	public Historique() {
	}

	public Historique(Departement departement, Pet pet, User user, Date debutSejour) {
		this.departement = departement;
		this.pet = pet;
		this.user = user;
		this.debutSejour = debutSejour;
	}

	public Historique(Departement departement, Pet pet, User user, Date debutSejour, Date finSejour) {
		this.departement = departement;
		this.pet = pet;
		this.user = user;
		this.debutSejour = debutSejour;
		this.finSejour = finSejour;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idhistorique", unique = true, nullable = false)
	public Integer getIdhistorique() {
		return this.idhistorique;
	}

	public void setIdhistorique(Integer idhistorique) {
		this.idhistorique = idhistorique;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deptid", nullable = false)
	public Departement getDepartement() {
		return this.departement;
	}

	public void setDepartement(Departement departement) {
		this.departement = departement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idpet", nullable = false)
	public Pet getPet() {
		return this.pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "debut_sejour", nullable = false, length = 19)
	public Date getDebutSejour() {
		return this.debutSejour;
	}

	public void setDebutSejour(Date debutSejour) {
		this.debutSejour = debutSejour;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fin_sejour", length = 19)
	public Date getFinSejour() {
		return this.finSejour;
	}

	public void setFinSejour(Date finSejour) {
		this.finSejour = finSejour;
	}

}
