package fr.formation.inti.entities;
// Generated 16 janv. 2020 17:12:14 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import fr.formation.inti.entities.User;

/**
 * Individual generated by hbm2java
 */
@Entity
@Table(name = "individual", catalog = "adopt_a_pet")
public class Individual implements java.io.Serializable {

	private Integer idindvidual;
	private User user;
	private String firstName;
	private String lastName;
	private String mail;
	private String tel;
	private String adress;
	private String city;
	private int postalCode;

	public Individual() {
	}

	public Individual(User user, String firstName, String lastName, String mail, String tel, int postalCode) {
		this.user = user;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mail = mail;
		this.tel = tel;
		this.postalCode = postalCode;
	}

	public Individual(User user, String firstName, String lastName, String mail, String tel, String adress, String city,
			int postalCode) {
		this.user = user;
		this.firstName = firstName;
		this.lastName = lastName;
		this.mail = mail;
		this.tel = tel;
		this.adress = adress;
		this.city = city;
		this.postalCode = postalCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idindvidual", unique = true, nullable = false)
	public Integer getIdindvidual() {
		return this.idindvidual;
	}

	public void setIdindvidual(Integer idindvidual) {
		this.idindvidual = idindvidual;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "first_name", nullable = false, length = 45)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 45)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "mail", nullable = false, length = 45)
	public String getMail() {
		return this.mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	@Column(name = "tel", nullable = false, length = 45)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "adress", length = 45)
	public String getAdress() {
		return this.adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "postal_code", nullable = false)
	public int getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(int postalCode) {
		this.postalCode = postalCode;
	}

}
