package fr.formation.inti.entities;
// Generated 15 janv. 2020 16:53:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pet generated by hbm2java
 */
@Entity
@Table(name = "pet", catalog = "adopt_a_pet")
public class Pet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idpet;
	private Categorie categorie;
	private User user;
	private String name;
	private String race;
	private String age;
	private int deptid;
	private Set<Transfert> transferts = new HashSet<Transfert>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Historique> historiques = new HashSet<Historique>(0);
	private Set<Adoption> adoptions = new HashSet<Adoption>(0);

	public Pet() {
	}

	public Pet(Categorie categorie, User user, String name, int deptid) {
		this.categorie = categorie;
		this.user = user;
		this.name = name;
		this.deptid = deptid;
	}

	public Pet(Categorie categorie, User user, String name, String race, String age, int deptid,
			Set<Transfert> transferts, Set<User> users, Set<Historique> historiques, Set<Adoption> adoptions) {
		this.categorie = categorie;
		this.user = user;
		this.name = name;
		this.race = race;
		this.age = age;
		this.deptid = deptid;
		this.transferts = transferts;
		this.users = users;
		this.historiques = historiques;
		this.adoptions = adoptions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idpet", unique = true, nullable = false)
	public Integer getIdpet() {
		return this.idpet;
	}

	public void setIdpet(Integer idpet) {
		this.idpet = idpet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcat", nullable = false)
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iduser", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "race", length = 45)
	public String getRace() {
		return this.race;
	}

	public void setRace(String race) {
		this.race = race;
	}

	@Column(name = "age", length = 45)
	public String getAge() {
		return this.age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	@Column(name = "deptid", nullable = false)
	public int getDeptid() {
		return this.deptid;
	}

	public void setDeptid(int deptid) {
		this.deptid = deptid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<Transfert> getTransferts() {
		return this.transferts;
	}

	public void setTransferts(Set<Transfert> transferts) {
		this.transferts = transferts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<Historique> getHistoriques() {
		return this.historiques;
	}

	public void setHistoriques(Set<Historique> historiques) {
		this.historiques = historiques;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pet")
	public Set<Adoption> getAdoptions() {
		return this.adoptions;
	}

	public void setAdoptions(Set<Adoption> adoptions) {
		this.adoptions = adoptions;
	}

}
