package fr.formation.inti.entities;
// Generated 15 janv. 2020 16:53:54 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Title generated by hbm2java
 */
@Entity
@Table(name = "title", catalog = "adopt_a_pet")
public class Title implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer idtitle;
	private String title;
	private Set<User> users = new HashSet<User>(0);

	public Title() {
	}

	public Title(String title) {
		this.title = title;
	}

	public Title(String title, Set<User> users) {
		this.title = title;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idtitle", unique = true, nullable = false)
	public Integer getIdtitle() {
		return this.idtitle;
	}

	public void setIdtitle(Integer idtitle) {
		this.idtitle = idtitle;
	}

	@Column(name = "title", nullable = false, length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "title")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
