-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 10:54:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema adopt_a_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `adopt_a_pet` DEFAULT CHARACTER SET latin1 ;
USE `adopt_a_pet` ;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`adoption`
-- -----------------------------------------------------
CREATE TABLE `adoption` (
  `idadoption` int(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `idpet` int(11) NOT NULL,
  `date_demande` datetime NOT NULL,
  `validation_profile` tinyint(4) NOT NULL,
  `validation_paiement` tinyint(4) NOT NULL,
  PRIMARY KEY (`idadoption`),
  KEY `iduser_user_adoption_idx` (`iduser`),
  KEY `idpet_pet_adoption_idx` (`idpet`),
  CONSTRAINT `idpet_pet_adoption` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_adoption` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`centre`
-- -----------------------------------------------------
CREATE TABLE `centre` (
  `idcentre` int(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `name` varchar(45) NOT NULL,
  `deptid` int(11) NOT NULL,
  `tel` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `postal_code` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`idcentre`),
  KEY `iduser_user_centre_idx` (`iduser`),
  KEY `deptid_departement_centre_idx` (`deptid`),
  CONSTRAINT `deptid_departement_centre` FOREIGN KEY (`deptid`) REFERENCES `departement` (`deptid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_centre` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`departement`
-- -----------------------------------------------------
CREATE TABLE `departement` (
  `deptid` int(11) NOT NULL,
  `departement_code` int(11) NOT NULL,
  `name` varchar(45) NOT NULL,
  PRIMARY KEY (`deptid`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- phpMyAdmin SQL Dump
-- version 4.0.6deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Nov 09, 2013 at 06:10 PM
-- Server version: 5.5.34-0ubuntu0.13.10.1
-- PHP Version: 5.5.3-1ubuntu2

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;




-- -----------------------------------------------------
-- Table `adopt_a_pet`.`historique`
-- -----------------------------------------------------
CREATE TABLE `historique` (
  `idhistorique` int(11) NOT NULL AUTO_INCREMENT,
  `idpet` int(11) NOT NULL,
  `iduser` int(11) NOT NULL,
  `deptid` int(11) NOT NULL,
  `debut_sejour` datetime NOT NULL,
  `fin_sejour` datetime DEFAULT NULL,
  PRIMARY KEY (`idhistorique`),
  KEY `idpet_idx` (`idpet`),
  KEY `deptid_idx` (`deptid`),
  KEY `iduser_user_historique_idx` (`iduser`),
  CONSTRAINT `deptid_departement_historique` FOREIGN KEY (`deptid`) REFERENCES `departement` (`deptid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `idpet_pet_historique` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_historique` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`individual`
-- -----------------------------------------------------
CREATE TABLE `individual` (
  `idindvidual` INT(11) NOT NULL AUTO_INCREMENT,
  `iduser` int(11) NOT NULL,
  `first_name` varchar(45) NOT NULL,
  `last_name` varchar(45) NOT NULL,
  `mail` varchar(45) NOT NULL,
  `tel` varchar(45) NOT NULL,
  `adress` varchar(45) DEFAULT NULL,
  `city` varchar(45) DEFAULT NULL,
  `postal_code` int(11) NOT NULL,
  PRIMARY KEY (`idindvidual`),
  KEY `iduser_user_individual_idx` (`iduser`),
  CONSTRAINT `iduser_user_individual` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`paiement`
-- -----------------------------------------------------
CREATE TABLE `paiement` (
  `idpaiement` int(11) NOT NULL AUTO_INCREMENT,
  `idadoption` int(11) NOT NULL,
  PRIMARY KEY (`idpaiement`),
  KEY `idadoption_adoption_paiement_idx` (`idadoption`),
  CONSTRAINT `idadoption_adoption_paiement` FOREIGN KEY (`idadoption`) REFERENCES `adoption` (`idadoption`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`title`
-- -----------------------------------------------------
CREATE TABLE `title` (
  `idtitle` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(45) NOT NULL,
  PRIMARY KEY (`idtitle`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- -----------------------------------------------------
-- Table `adopt_a_pet`.`transfert`
-- -----------------------------------------------------
CREATE TABLE `transfert` (
  `idtransfert` int(11) NOT NULL AUTO_INCREMENT,
  `idpet` int(11) NOT NULL,
  `iduser` int(11) NOT NULL,
  `new_id_user` int(11) NOT NULL,
  PRIMARY KEY (`idtransfert`),
  KEY `idpet_pet_transfert_idx` (`idpet`),
  KEY `iduser_user_transfert_idx` (`iduser`),
  KEY `newiduser_user_transfert_idx` (`new_id_user`),
  CONSTRAINT `idpet_pet_transfert` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_transfert` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `newiduser_user_transfert` FOREIGN KEY (`new_id_user`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`categorie`
-- -----------------------------------------------------
CREATE TABLE `categorie` (
  `idcat` int(11) NOT NULL AUTO_INCREMENT,
  `categorie` varchar(45) NOT NULL,
  PRIMARY KEY (`idcat`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

- -----------------------------------------------------
-- Table `adopt_a_pet`.`user`
-- -----------------------------------------------------
CREATE TABLE `user` (
  `iduser` int(11) NOT NULL AUTO_INCREMENT,
  `idpet` int(11),
  `deptid` int(11) NOT NULL,
  `username` varchar(45) NOT NULL,
  `password` varchar(45) NOT NULL,
  `idtitle` int(11) NOT NULL,
  `date_creation` datetime DEFAULT NULL,
  `date_fermeture` datetime DEFAULT NULL,
  PRIMARY KEY (`iduser`),
  KEY `idpet_pet_user_idx` (`idpet`),
  KEY `deptid_departement_user_idx` (`deptid`),
  KEY `idtitle_title_user_idx` (`idtitle`),
  CONSTRAINT `deptid_departement_user` FOREIGN KEY (`deptid`) REFERENCES `departement` (`deptid`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `idpet_pet_user` FOREIGN KEY (`idpet`) REFERENCES `pet` (`idpet`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `idtitle_title_user` FOREIGN KEY (`idtitle`) REFERENCES `title` (`idtitle`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- -----------------------------------------------------
-- Table `adopt_a_pet`.`pet`
-- -----------------------------------------------------
CREATE TABLE `pet` (
  `idpet` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `idcat` int(11) NOT NULL,
  `race` varchar(45) DEFAULT NULL,
  `age` varchar(45) DEFAULT NULL,
  `iduser` int(11) NOT NULL,
  `deptid` int(11) NOT NULL,
  PRIMARY KEY (`idpet`),
  KEY `idcat_categorie_pet_idx` (`idcat`),
  KEY `iduser_user_pet_idx` (`iduser`),
  CONSTRAINT `idcat_categorie_pet` FOREIGN KEY (`idcat`) REFERENCES `categorie` (`idcat`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `iduser_user_pet` FOREIGN KEY (`iduser`) REFERENCES `user` (`iduser`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

